[package]
name = "jsdotlua/regex"
description = "https://github.com/jsdotlua/regex-lua"
version = "1.0.0"
license = "MIT"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
LuauPolyfill = "core-packages/luau-polyfill@1.2.3"
